[[services]]
name = "test"
command = "sh"
args = ["-c", "exit 1"]

[[services]]
name = "always-fail"
command = "idfkskibiditoiletistgifthisisacommand"

# [[services]]
# name = "trap-test"
# command = "sh"
# args = ["-c", "trap '' TERM; sleep 1000"]

[[services]]
name = "ticker"
command = "sh"
args = ["-c", "for i in 1 2 3; do echo tick $i; echo oops $i >&2; sleep 1; done; exit 1"]
